baseURL = 'https://puppygirl.onl/'
languageCode = 'en-us'
title = "puppygirl.onl"
description = ""
author = "lulu"
enableRobotsTXT = true
theme = "risotto"
themesDir = "themes/"

sectionPagesMenu = "main"

[outputs]
  home = ['html']
  section = ['html', 'rss', 'json']
  page = ['html']

[params]
noindex = false
[params.theme]
palette = "gruvbox-light"

[markup]
  [markup.highlight]
    noClasses = false
    style = 'gruvbox-light'

  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
  [markup.goldmark.renderer]
    unsafe=true
